---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont-1
          image: pavan494909v/devapp:appimage
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockerhub

#kubectl create secret generic dockerhub -secret--docker-server=docker.io --from-literal=username=pavan [root@ip-172-31-81-0 ~]# kubectl create secret docker-registry dockerhub --docker-server=https://index.docker.io/v1 --docker-username=username=pavan49909v --docker-password=


---
apiVersion: v1
kind: Service
metadata:
  name: appsvc
spec:
  type: LoadBalancer
  selector:
    app: swiggy
  ports:
    - port: 8080
      targetPort: 8080
